### ISSUE TITLE
Run models API returns Internal Server Error

### ISSUE THREAD

**Issue by edwardzjl** [dbt-labs/dbt-server#113]
POST to /run returns Internal Server Error:
```
TypeError: Object of type datetime is not JSON serializable
```

The `RunExecutionResult` has a `generated_at` field of type `datetime.datetime`, and in fastapi 0.68.1 it is not supported to serialize `datetime.datetime` to json.

Update fastapi to the latest release (0.86.0) will solve this problem.

**Comment by joemirizio** [comment]
Yeah, more specifically, this version of fastapi doesn't properly handle serialization of nested properties in dataclasses. Looks like it was [fixed in `0.81.0`](https://github.com/tiangolo/fastapi/pull/3607).

If changing the version is not possible, another workaround would be to explicitly call `dataclasses.asdict` on the results or similarly call `jsonable_encoder` twice.
```python
encoded_results = jsonable_encoder(jsonable_encoder(results))
```

**Comment by lostmygithubaccount** [comment]
hello! apologies for the slow response here. there should be fixed in a future release -- we've fixed this in our own testing internally either with the solution above or similarly `json_encoder(results.to_dict())`

that `/run` endpoint is not officially supported yet (perhaps despite clear documentation) -- stay tuned for that and more soon!

**Comment by racheldaniel** [comment]
Closing this issue, as the endpoint in question has been deprecated in favor of the `/invocations` endpoint and should not have the same bug.
