### ISSUE TITLE
Documentation for how to start server and what are the config parameter  available etc

### ISSUE THREAD

**Issue by sivankumar86** [dbt-labs/dbt-server#199]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I want to install dt-server however, I could not find documentation on how to install and how to configure dbt-project.

**Comment by vladimirdinolov-8451** [comment]
Yes, I would like to second this. The closest thing to documentation is in the `CONTRIBUTING.md` file.

**Comment by lsabreu96** [comment]
+1 on that

**Comment by JavierLopezT** [comment]
+1

**Comment by Uranium2** [comment]
This would be very appreciated. Since the old project is getting dreprecated, I wanted to jump directly on `dbt-server`. But it's kind of a nightmare to understand want to install, want to run to get everything running. I got a custom docker image by looking up the Dockerfile, but nothing mention redis server. Why is it needed? How is it installed in this project? So many questions on how to do things.
